# Generated by Django 6.0.4 on 2026-06-02 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DidYouKnowFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('precolonial', 'Pre-Colonial Era'), ('colonial', 'Colonial Era'), ('independence', 'Independence Struggle'), ('post_independence', 'Post Independence'), ('culture', 'Culture & Heritage'), ('leaders', 'Historical Leaders')], default='post_independence', max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('arrest', 'Arrest & Police'), ('land', 'Land & Property'), ('employment', 'Employment'), ('health', 'Health'), ('education', 'Education'), ('family', 'Family'), ('corruption', 'Corruption'), ('voting', 'Voting'), ('technology', 'Technology'), ('other', 'Other')], default='other', max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('helpful_count', models.IntegerField(default=0)),
                ('not_helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('constituency', models.CharField(max_length=200)),
                ('party', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('term_start', models.DateField()),
                ('term_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('result_code', models.IntegerField()),
                ('result_desc', models.CharField(max_length=200)),
                ('is_successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('national', 'National Holiday'), ('county', 'County Event'), ('participation', 'Public Participation'), ('community', 'Community Event')], max_length=50)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('county', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('theft', 'Theft / Robbery'), ('assault', 'Assault / GBV'), ('corruption', 'Corruption / Bribery'), ('land', 'Land Dispute'), ('police', 'Police Misconduct'), ('domestic', 'Domestic Violence'), ('cyber', 'Cybercrime'), ('other', 'Other')], max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('location_description', models.TextField()),
                ('incident_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('evidence_photo', models.URLField(blank=True, null=True)),
                ('evidence_video', models.URLField(blank=True, null=True)),
                ('witness_name', models.CharField(blank=True, max_length=200)),
                ('witness_phone', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Under Review'), ('authorities', 'With Authorities'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='submitted', max_length=50)),
                ('anonymity', models.CharField(choices=[('full', 'Fully Anonymous'), ('pseudo', 'Pseudonymous'), ('public_map', 'Show on Map'), ('named', 'Named')], default='full', max_length=20)),
                ('is_visible_on_map', models.BooleanField(default=False)),
                ('police_station', models.CharField(blank=True, max_length=200)),
                ('officer_badge', models.CharField(blank=True, max_length=50)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MPPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('attendance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bills_sponsored', models.IntegerField(default=0)),
                ('bills_passed', models.IntegerField(default=0)),
                ('motions_contributed', models.IntegerField(default=0)),
                ('questions_asked', models.IntegerField(default=0)),
                ('projects_completed', models.IntegerField(default=0)),
                ('projects_ongoing', models.IntegerField(default=0)),
                ('projects_delayed', models.IntegerField(default=0)),
                ('grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Average'), ('D', 'Poor'), ('F', 'Very Poor')], default='C', max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='accounts.mp')),
            ],
            options={
                'unique_together': {('mp', 'year')},
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('check_in_method', models.CharField(choices=[('gps', 'GPS Location'), ('qr', 'QR Code'), ('manual', 'Manual')], default='gps', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_attended', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='accounts.publicevent')),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.CreateModel(
            name='VotingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=200)),
                ('election_date', models.DateField()),
                ('polling_station', models.CharField(max_length=200)),
                ('has_voted', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'election_name')},
            },
        ),
    ]
