# Generated by Django 6.0.4 on 2026-05-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('article_number', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('full_text', models.TextField()),
                ('simplified_english', models.TextField(blank=True)),
                ('simplified_swahili', models.TextField(blank=True)),
                ('topic', models.CharField(choices=[('rights', 'Bill of Rights'), ('land', 'Land and Environment'), ('leadership', 'Leadership and Integrity'), ('devolution', 'Devolution'), ('citizenship', 'Citizenship'), ('judiciary', 'Judiciary'), ('other', 'Other')], default='other', max_length=50)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
